// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model.proto

package contract

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Endpoint struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NetworkId            string            `protobuf:"bytes,2,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	Host                 string            `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Ports                []int32           `protobuf:"varint,4,rep,packed,name=ports,proto3" json:"ports,omitempty"`
	Labels               map[string]string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Endpoint) Reset()         { *m = Endpoint{} }
func (m *Endpoint) String() string { return proto.CompactTextString(m) }
func (*Endpoint) ProtoMessage()    {}
func (*Endpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0}
}

func (m *Endpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Endpoint.Unmarshal(m, b)
}
func (m *Endpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Endpoint.Marshal(b, m, deterministic)
}
func (m *Endpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Endpoint.Merge(m, src)
}
func (m *Endpoint) XXX_Size() int {
	return xxx_messageInfo_Endpoint.Size(m)
}
func (m *Endpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Endpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Endpoint proto.InternalMessageInfo

func (m *Endpoint) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Endpoint) GetNetworkId() string {
	if m != nil {
		return m.NetworkId
	}
	return ""
}

func (m *Endpoint) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Endpoint) GetPorts() []int32 {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *Endpoint) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type Endpoints struct {
	Endpoints            []*Endpoint `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Endpoints) Reset()         { *m = Endpoints{} }
func (m *Endpoints) String() string { return proto.CompactTextString(m) }
func (*Endpoints) ProtoMessage()    {}
func (*Endpoints) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{1}
}

func (m *Endpoints) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Endpoints.Unmarshal(m, b)
}
func (m *Endpoints) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Endpoints.Marshal(b, m, deterministic)
}
func (m *Endpoints) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Endpoints.Merge(m, src)
}
func (m *Endpoints) XXX_Size() int {
	return xxx_messageInfo_Endpoints.Size(m)
}
func (m *Endpoints) XXX_DiscardUnknown() {
	xxx_messageInfo_Endpoints.DiscardUnknown(m)
}

var xxx_messageInfo_Endpoints proto.InternalMessageInfo

func (m *Endpoints) GetEndpoints() []*Endpoint {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

type EndpointFilter struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EndpointFilter) Reset()         { *m = EndpointFilter{} }
func (m *EndpointFilter) String() string { return proto.CompactTextString(m) }
func (*EndpointFilter) ProtoMessage()    {}
func (*EndpointFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{2}
}

func (m *EndpointFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndpointFilter.Unmarshal(m, b)
}
func (m *EndpointFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndpointFilter.Marshal(b, m, deterministic)
}
func (m *EndpointFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndpointFilter.Merge(m, src)
}
func (m *EndpointFilter) XXX_Size() int {
	return xxx_messageInfo_EndpointFilter.Size(m)
}
func (m *EndpointFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_EndpointFilter.DiscardUnknown(m)
}

var xxx_messageInfo_EndpointFilter proto.InternalMessageInfo

func (m *EndpointFilter) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EndpointFilter) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func init() {
	proto.RegisterType((*Endpoint)(nil), "letitfail.Endpoint")
	proto.RegisterMapType((map[string]string)(nil), "letitfail.Endpoint.LabelsEntry")
	proto.RegisterType((*Endpoints)(nil), "letitfail.Endpoints")
	proto.RegisterType((*EndpointFilter)(nil), "letitfail.EndpointFilter")
}

func init() { proto.RegisterFile("model.proto", fileDescriptor_4c16552f9fdb66d8) }

var fileDescriptor_4c16552f9fdb66d8 = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0x49, 0xba, 0x5d, 0xcc, 0x14, 0x16, 0x19, 0x3d, 0x04, 0x41, 0x2c, 0x3d, 0xf5, 0x54,
	0xf0, 0x0f, 0xf8, 0xe7, 0xe0, 0x6d, 0x05, 0xc1, 0x53, 0xbf, 0x80, 0x74, 0xc9, 0x88, 0x61, 0x63,
	0x53, 0xd2, 0x51, 0xd9, 0x4f, 0xea, 0xd7, 0x91, 0xcd, 0x36, 0xae, 0xa0, 0xb7, 0x79, 0x2f, 0x8f,
	0xcc, 0x6f, 0x1e, 0x14, 0x6f, 0xde, 0x90, 0x6b, 0x86, 0xe0, 0xd9, 0xa3, 0x72, 0xc4, 0x96, 0x5f,
	0x3a, 0xeb, 0xaa, 0x2f, 0x01, 0x07, 0xcb, 0xde, 0x0c, 0xde, 0xf6, 0x8c, 0x0b, 0x90, 0xd6, 0x68,
	0x51, 0x8a, 0x5a, 0xb5, 0xd2, 0x1a, 0x3c, 0x05, 0xe8, 0x89, 0x3f, 0x7d, 0x58, 0x3f, 0x5b, 0xa3,
	0x65, 0xf4, 0xd5, 0xe4, 0x3c, 0x1a, 0x44, 0x98, 0xbd, 0xfa, 0x91, 0x75, 0x16, 0x1f, 0xe2, 0x8c,
	0xc7, 0x90, 0x0f, 0x3e, 0xf0, 0xa8, 0x67, 0x65, 0x56, 0xe7, 0xed, 0x4e, 0xe0, 0x35, 0xcc, 0x5d,
	0xb7, 0x22, 0x37, 0xea, 0xbc, 0xcc, 0xea, 0xe2, 0xe2, 0xac, 0xf9, 0x21, 0x68, 0xd2, 0xf6, 0xe6,
	0x29, 0x26, 0x96, 0x3d, 0x87, 0x4d, 0x3b, 0xc5, 0x4f, 0x6e, 0xa1, 0xf8, 0x65, 0xe3, 0x21, 0x64,
	0x6b, 0xda, 0x4c, 0x84, 0xdb, 0x71, 0xbb, 0xef, 0xa3, 0x73, 0xef, 0x34, 0xd1, 0xed, 0xc4, 0x9d,
	0xbc, 0x11, 0xd5, 0x3d, 0xa8, 0xf4, 0xf5, 0x88, 0xe7, 0xa0, 0x28, 0x09, 0x2d, 0x22, 0xc3, 0xd1,
	0x3f, 0x0c, 0xed, 0x3e, 0x55, 0x5d, 0xc1, 0x22, 0xd9, 0x0f, 0xd6, 0x31, 0x85, 0x3f, 0xf5, 0xa4,
	0xfb, 0xe5, 0xfe, 0xfe, 0xd5, 0x3c, 0x36, 0x7c, 0xf9, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x13, 0xbc,
	0x83, 0x9e, 0x70, 0x01, 0x00, 0x00,
}
