// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package contract

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListCommand struct {
	Page                 int64    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCommand) Reset()         { *m = ListCommand{} }
func (m *ListCommand) String() string { return proto.CompactTextString(m) }
func (*ListCommand) ProtoMessage()    {}
func (*ListCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *ListCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCommand.Unmarshal(m, b)
}
func (m *ListCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCommand.Marshal(b, m, deterministic)
}
func (m *ListCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCommand.Merge(m, src)
}
func (m *ListCommand) XXX_Size() int {
	return xxx_messageInfo_ListCommand.Size(m)
}
func (m *ListCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCommand.DiscardUnknown(m)
}

var xxx_messageInfo_ListCommand proto.InternalMessageInfo

func (m *ListCommand) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

type Endpoints struct {
	Endpoints            []*Endpoint `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Endpoints) Reset()         { *m = Endpoints{} }
func (m *Endpoints) String() string { return proto.CompactTextString(m) }
func (*Endpoints) ProtoMessage()    {}
func (*Endpoints) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *Endpoints) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Endpoints.Unmarshal(m, b)
}
func (m *Endpoints) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Endpoints.Marshal(b, m, deterministic)
}
func (m *Endpoints) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Endpoints.Merge(m, src)
}
func (m *Endpoints) XXX_Size() int {
	return xxx_messageInfo_Endpoints.Size(m)
}
func (m *Endpoints) XXX_DiscardUnknown() {
	xxx_messageInfo_Endpoints.DiscardUnknown(m)
}

var xxx_messageInfo_Endpoints proto.InternalMessageInfo

func (m *Endpoints) GetEndpoints() []*Endpoint {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

func init() {
	proto.RegisterType((*ListCommand)(nil), "letitfail.ListCommand")
	proto.RegisterType((*Endpoints)(nil), "letitfail.Endpoints")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xcc, 0x49, 0x2d, 0xc9, 0x2c,
	0x49, 0x4b, 0xcc, 0xcc, 0x91, 0xe2, 0xce, 0xcd, 0x4f, 0x49, 0xcd, 0x81, 0x88, 0x2b, 0x29, 0x72,
	0x71, 0xfb, 0x64, 0x16, 0x97, 0x38, 0xe7, 0xe7, 0xe6, 0x26, 0xe6, 0xa5, 0x08, 0x09, 0x71, 0xb1,
	0x14, 0x24, 0xa6, 0xa7, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x30, 0x07, 0x81, 0xd9, 0x4a, 0x76, 0x5c,
	0x9c, 0xae, 0x79, 0x29, 0x05, 0xf9, 0x99, 0x79, 0x25, 0xc5, 0x42, 0x86, 0x5c, 0x9c, 0xa9, 0x30,
	0x8e, 0x04, 0xa3, 0x02, 0xb3, 0x06, 0xb7, 0x91, 0xb0, 0x1e, 0xdc, 0x6c, 0x3d, 0x98, 0xc2, 0x20,
	0x84, 0x2a, 0x23, 0x0f, 0x2e, 0x01, 0xb8, 0x70, 0x6a, 0x7a, 0x66, 0x71, 0x49, 0x51, 0xa5, 0x90,
	0x09, 0x17, 0x4b, 0x4e, 0x66, 0x71, 0x89, 0x90, 0x18, 0x92, 0x5e, 0x24, 0x77, 0x48, 0x89, 0x60,
	0x31, 0xb3, 0xd8, 0x89, 0x2b, 0x8a, 0x23, 0x39, 0x3f, 0xaf, 0xa4, 0x28, 0x31, 0xb9, 0x24, 0x80,
	0x21, 0x89, 0x0d, 0xec, 0x03, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe1, 0xd1, 0xe9, 0x1c,
	0xea, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EndpointRegistryClient is the client API for EndpointRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EndpointRegistryClient interface {
	List(ctx context.Context, in *ListCommand, opts ...grpc.CallOption) (*Endpoints, error)
}

type endpointRegistryClient struct {
	cc *grpc.ClientConn
}

func NewEndpointRegistryClient(cc *grpc.ClientConn) EndpointRegistryClient {
	return &endpointRegistryClient{cc}
}

func (c *endpointRegistryClient) List(ctx context.Context, in *ListCommand, opts ...grpc.CallOption) (*Endpoints, error) {
	out := new(Endpoints)
	err := c.cc.Invoke(ctx, "/letitfail.EndpointRegistry/list", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EndpointRegistryServer is the server API for EndpointRegistry service.
type EndpointRegistryServer interface {
	List(context.Context, *ListCommand) (*Endpoints, error)
}

// UnimplementedEndpointRegistryServer can be embedded to have forward compatible implementations.
type UnimplementedEndpointRegistryServer struct {
}

func (*UnimplementedEndpointRegistryServer) List(ctx context.Context, req *ListCommand) (*Endpoints, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}

func RegisterEndpointRegistryServer(s *grpc.Server, srv EndpointRegistryServer) {
	s.RegisterService(&_EndpointRegistry_serviceDesc, srv)
}

func _EndpointRegistry_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointRegistryServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/letitfail.EndpointRegistry/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointRegistryServer).List(ctx, req.(*ListCommand))
	}
	return interceptor(ctx, in, info, handler)
}

var _EndpointRegistry_serviceDesc = grpc.ServiceDesc{
	ServiceName: "letitfail.EndpointRegistry",
	HandlerType: (*EndpointRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "list",
			Handler:    _EndpointRegistry_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
